server:
  port: 9991
  shutdown: GRACEFUL

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true # debug purpose
  datasource:
    url: {DATASOURCE_URL}
    username: {DATASOURCE_USERNAME}
    password: {DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jackson:
    default-property-inclusion: non_null

  cache:
    type: redis
  redis:
    host: {REDIS_HOST}
    port: 6379
    password: {REDIS_PASSWORD}
    database: 1